name: docker image
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ./build.sh

    - name: copy daemon.json
      run: sudo cp daemon.json /etc/docker/daemon.json

    - name: restart docker
      run: sudo systemctl restart docker

    - name: ip addr show
      run: ip addr show

    - name: create network
      run: ./network.sh

    - name: run the Docker image
      run: |
        for i in {1..300}; do
          ./run.sh -d
        done

    - name: ip addr show
      run: ip addr show

    - name: send multicast
      run: ./multicast_sender.py macvlan-shim 5
